### ISSUE TITLE
The "snapshot" handle is leaked

### ISSUE THREAD

**Issue by roflcopter4** [plicease/Win32-Getppid#6]
I was looking around for some Win32 implementation of `getppid` ~to steal~ *AHEM* borrow with proper credit given and I couldn't help but notice that this one has a minor issue. You don't close the `HANDLE` returned by `CreateToolhelp32Snapshot`. [Per Microsoft's documentation](https://docs.microsoft.com/en-us/windows/win32/api/tlhelp32/nf-tlhelp32-createtoolhelp32snapshot) this handle must be closed to "destroy the snapshot".

In theory I could have made a pull request or something but blegh. It's one line of code.

**Comment by plicease** [comment]
I really appreciate your taking the time to report this!  I believe #7 should address this.
